version: 2
jobs:
  build:
    working_directory: ~/dlbrt_blockchain
    docker:
       - image: circleci/node:10.8.0
    steps:
      - checkout
      - run:
          name: update the package manager
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install the dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Install code coverage dependencies
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name: run the tests and update the coverage
          command: | 
            ./cc-test-reporter before-build
          npm test
           ./cc-test-reporter after-build --coverage-input-type lcov --exit-code $?
      - store_artifacts:
          path: coverage
          prefix: coverage
