version: 2
jobs:
  build:
    working_directory: ~/dlbrt_blockchain
    docker:
       - image: circleci/node:10.8.0
    steps:
      - checkout
      - run:
          name: update the package manager
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install the dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: run tests
          command: cd src && npm test
    
